// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_j1PK49CnDY9K4wa8_S9SCcSXhL801M',
    appId: '1:501291861073:web:15848f11615e3b8e8ae470',
    messagingSenderId: '501291861073',
    projectId: 'gean-truck',
    authDomain: 'gean-truck.firebaseapp.com',
    storageBucket: 'gean-truck.firebasestorage.app',
    measurementId: 'G-V9HGR1NZ9B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8gUxkLOF5BPOM3vsooQySCbCcUK4iUyM',
    appId: '1:501291861073:android:7d36f103b512c2818ae470',
    messagingSenderId: '501291861073',
    projectId: 'gean-truck',
    storageBucket: 'gean-truck.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNx_JqdZFDJRkTsqLqzyri8sDFwQya8RI',
    appId: '1:501291861073:ios:52a2e521e11cf2c18ae470',
    messagingSenderId: '501291861073',
    projectId: 'gean-truck',
    storageBucket: 'gean-truck.firebasestorage.app',
    iosBundleId: 'com.example.geantruck',
  );
}
