import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../services/firestore_service.dart';
import '../models/truck_model.dart';
import 'package:firebase_auth/firebase_auth.dart';

class AddTruckScreen extends StatefulWidget {
  @override
  _AddTruckScreenState createState() => _AddTruckScreenState();
}

class _AddTruckScreenState extends State<AddTruckScreen> {
  final _nameController = TextEditingController();
  final _plateController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    final firestoreService = FirestoreService();
    final user = Provider.of<User?>(context);

    return Scaffold(
      appBar: AppBar(title: Text('Adicionar Caminhão')),
      body: Padding(
        padding: const EdgeInsets.all(16.0),
        child: Column(
          children: [
            TextField(
              controller: _nameController,
              decoration: InputDecoration(labelText: 'Nome do Caminhão'),
            ),
            TextField(
              controller: _plateController,
              decoration: InputDecoration(labelText: 'Placa'),
            ),
            SizedBox(height: 20),
            ElevatedButton(
              onPressed: () async {
                if (user != null) {
                  await firestoreService.addTruck(
                    user.uid,
                    TruckModel(
                      id: '', // ID will be generated by Firestore
                      name: _nameController.text,
                      plate: _plateController.text,
                    ),
                  );
                  Navigator.pop(context);
                }
              },
              child: Text('Adicionar'),
            ),
          ],
        ),
      ),
    );
  }
}
